### ISSUE TITLE
add-ons sidebar display

### ISSUE THREAD

**Issue by atomGit** [Quicksaver/OmniSidebar#71]
hi Quicksaver!

personally, i much prefer the more minimal, optimized layout for extensions as in AIOS where only the title is shown until a list item is clicked

also, it seems the list is rebuilt every time the sidebar add-on panel is opened which makes it a little slow to display

lastly, the font size is too small

**Comment by atomGit** [comment]
please consider just not re-styling the font size for the add-ons panel - that tiny font is not easily readable at all in my case :)
thanks

**Comment by Quicksaver** [comment]
Could you give the latest beta version 1.5.1b2 a try? (at the top of https://addons.mozilla.org/firefox/addon/omnisidebar/versions/) I've made many changes to the add-ons sidebar, to make it easier to read and use; those userstyles did come in handy, thanks for those. :)

There is however one of your suggestions I don't particularly like, to always hide the buttons until the add-on is clicked. For instance, I use the addons sidebar all the time and I need those buttons constantly in many different add-ons. That behavior makes me need to click each add-on twice, one to show the buttons and another to "do whatever". Which is why I kept the buttons always visible at first.

However I can see how it looks better with the buttons hidden, so I decided to toy with an idea: show the buttons on moving the mouse over the add-on as well, so in most cases you still only need to click the add-on entry once even though the buttons are initially hidden.

I don't want to hide the buttons by default (without the mouseover) because I see it as a hassle like I mentioned. I could hide them (without the mouseover) via an option in the preferences, but that won't happen until I add the per-panel preferences (specific to each different sidebar, such as bookmarks, history, addons, etc). And to hide the addon entries by default without a preference to disable it, I think I would only do it like this (with the mouseover). I don't know what to decide here, so let me know what you guys think about this behavior, I'd really like your opinions. :)

**Comment by atomGit** [comment]
THANK YOU!
i can read the text now :)

it looks like you made the ext. title font bold - no need for that in my opinion - just the standard FF text is fine

the mouseover solution is great

**Comment by Quicksaver** [comment]
It was actually always bold (I never changed that), it was just too small for you to notice before I guess. :)

**Comment by Quicksaver** [comment]
Not yet, it's not finished I may still make some changes here and there. ;)

**Comment by atomGit** [comment]
sorry :)
one thing you could add is an add-on count - a/b - where a=total add-ons and b=enabled add-ons

**Comment by Quicksaver** [comment]
That'll come with the per-panels preferences. :)

**Comment by Keith94** [comment]
Nice work on the new styling.

There's a bug with the menu popups. They appear misaligned on the far right side, and it's impossible to click and drag the scrollbars. For example, install [Enhanced Steam](http://firefox.enhancedsteam.com/), go to its options and use the region menus near the bottom.

I do kinda like the [categories popup](https://df6a.https.cdn.softlayer.net/80DF6A/static.userstyles.org/style_screenshots/48731_additional_210.png) from banthaz's style. You can test it if you use this method: Via a bookmark, with the address “about:addons”, set to open in the sidebar. You could possibly add it as an optional thing later on.

Also for the add-on counter idea, there's a userstyle made for that [here](https://github.com/Infocatcher/UserStyles/tree/master/Addons_Manager_Counters) if it'll come in handy.

**Comment by Quicksaver** [comment]
> There's a bug with the menu popups. They appear misaligned on the far right side, and it's impossible to click and drag the scrollbars.

Right you are! Just uploaded beta version 1.5.1b6 with a fix for that, here's to hoping I didn't break anything else in the process.

> I do kinda like the categories popup from banthaz's style.

It is interesting indeed. Added it to my list of "thing to check out for the per-panels preferences", thanks for the suggestion!

**Comment by tophf** [comment]
Regardless of how I love OSB, I had to revert this commit (1eb58c4) for **addons.css** entirely, after unsuccessfully trying to tolerate the change for two days and then failing to override it with Stylish or userchrome.css due to lots of `!important` in the css (are those really needed?).

* What about adding an option to disable that squirmy jittery resizing of icons on mousehover and selection?

* And an option to bring back persistent control buttons \*might\* be nice because:

  1. the benefits of visually decluttering the lists don't outweigh the fidgety jittery appearance of buttons on mousehover - although this probably can be masked slightly by css `transition: opacity 0.2s`
  2. one of the most important uses at least for \*Addons\* sidepanel is to quickly perform an action like Enable/Disable/Options and so on, and each row may have different set of available buttons, so hiding them until mousehover introduces unneeded difficulties requiring a user to additionally move the mouse cursor horizontally to aim for the needed button when it appears.
  3. there are visual themes where the buttons are very small and unobtrusive

**Comment by Quicksaver** [comment]
@tophf, after a few days of using it myself more extensively, I have to agree. Some transitions would probably help, but overall I think this should go behind a preference as well.

I will push a quick update with all the fixes in the previous commit, except for the hover effects disabled. By the way, probably not all the ```!important``` are needed, but many really are, and it's just tedious, not to mention time consuming, to go through them all to see if they are or if I can find a greater degree of specificity to still apply the rules without them. But if you do run into any trouble with styling something and you think a few specific rule changes about this would help then let me know and I will definitely check it out!

@atomGit, I won't be adding this preference directly in the add-on just yet, because I still haven't worked out how to apply the panel-specific preferences (like this one). But I don't want you to live without it, since you were the one who suggested it in the first place. So you can get the hover effects back by applying the following stylesheet through stylish. I hope that will be enough, for now at least.

```CSS
.inSidebar .addon:not([selected]):not(:hover) .disabled-postfix,
.inSidebar .addon:not([selected]):not(:hover) .update-postfix {
	display: none !important;
}

.inSidebar .addon:not([selected]):not(:hover) :-moz-any(.description-outer-container,.control-container,.addon-control.update,.include-update,.update-available),
.inSidebar .addon:not([selected]):not(:hover) .status-container > hbox {
	visibility: collapse !important;
}

.inSidebar .addon:not([selected]):not(:hover) .advancedinfo-container {
	margin-top: -20px !important;
}

.inSidebar .addon:-moz-any([selected],:hover) .icon-container,
.inSidebar .addon:-moz-any([selected],:hover) .icon {
	max-width: 32px !important;
	max-height: 32px !important;
}

.inSidebar .addon:not([selected]):not(:hover) .icon-container,
.inSidebar .addon:not([selected]):not(:hover) .icon {
	max-width: 16px !important;
	max-height: 16px !important;
}

.inSidebar .addon .content-container { 
	margin: 3px 0 !important;
}
```
